version: "3.3"

services:
  db:
    image: postgres:12.0-alpine
    env_file:
      - gusto/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
