# Generated by Django 3.0.5 on 2021-02-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='dish')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='weight')),
                ('price', models.IntegerField(verbose_name='price')),
                ('category', models.CharField(choices=[('salads', 'Salads'), ('shashlyk', 'Shashlyk'), ('first-course', 'First Course'), ('second-course', 'Second Course'), ('set-lunch', 'Set Lunch'), ('meat-dishes', 'Meat Dishes'), ('pilaf', 'Pilaf'), ('fish', 'Fish'), ('alcohol', 'Alcohol'), ('drinks', 'Drinks'), ('snacks', 'Snacks')], default=0, max_length=128, verbose_name='category')),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
                'ordering': ['category', 'name'],
            },
        ),
    ]
